apps/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index_view, name="home-index"),
    path("create_view/", views.create_view, name="create-item"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.users.views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("apps.home.urls", namespace="home")),
    path("profile/", include("apps.users.urls", namespace="users")),
    path("@<username>/", profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path("", views.home_view, name="home"),
]

apps/home/models.py
from django.db import models
from colorfield.fields import ColorField


class Item(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class SiteSetting(models.Model):
    name = models.CharField(max_length=100)
    color = ColorField(default="#000000")
    logo = models.ImageField(upload_to="logo/", null=True, blank=True)

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect

from .models import Item


def index_view(request):
    items = Item.objects.all()
    context = {"items": items}
    return render(request, "home/index.html", context=context)


def create_view(request):
    if request.method == "POST":
        name = request.POST.get("name")
        item = Item(name=name)
        item.save()
        return HttpResponse(f'<li class="text-8xl fint-thin">{item.name}</li>')
    else:
        redirect("home:home-index")

templates/home/home.html
{% extends 'layouts/blank.html' %}

{% block content %} 

    <div class="max-w-4xl mx-auto px-8 py-24">
        <h1>New Project</h1>
    </div>

{% endblock %}

templates/home/index.html
{% extends 'layouts/blank.html' %}

{% block content %} 

    <div class="max-w-4xl mx-auto px-8 py-24">
        <h1>Most Popular:</h1>
        <ul id="item-list" class="mb-10">
            {% for item in items %}
            <li class="text-8xl font-thin">{{ item.name }}</li>
            {% endfor %}
        </ul>
        
        <form 
            hx-post="{% url 'home:create-item' %}"
            hx-target="#item-list" 
            hx-swap="beforeend" 
            _="on htmx:afterRequest reset() me" >
            {% csrf_token %}
            <div class="flex gap-5 max-w-lg ">
                <input type="text" name="name" placeholder="Add Item" autofocus />
                <button>Submit</button>
            </div>
        </form>
    </div>

{% endblock %}