apps/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index_view, name="home-index"),
    path("create_view/", views.create_view, name="create-item"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.users.views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("apps.home.urls", namespace="home")),
    path("profile/", include("apps.users.urls", namespace="users")),
    path("@<username>/", profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path("", views.home_view, name="home"),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path("", views.profile_view, name="profile"),
    path("edit/", views.profile_edit_view, name="profile-edit"),
    path("onboarding/", views.profile_edit_view, name="profile-onboarding"),
    path("settings/", views.profile_settings_view, name="profile-settings"),
    path(
        "emailchange/", views.profile_emailchange, name="profile-emailchange"
    ),
    path(
        "emailverify/", views.profile_emailverify, name="profile-emailverify"
    ),
    path("delete/", views.profile_delete_view, name="profile-delete"),
]

templates/includes/header.html
{% load static %}
<header class="flex items-center justify-between bg-gray-800 h-20 px-8 text-white sticky top-0 z-40"
{% if color %}style="background-color: {{ color }};"{% endif %}>
    <div>
        <a class="flex items-center gap-2" href="/">
            <img class="h-12" src="{% if logo %}{{ logo.url }}{% else %}{% static 'images/logo.png' %}{% endif %}" alt="Logo"/>
            <span class="text-lg font-bold">{% if request.tenant %}{{ request.tenant.name }}{% else %}Django Tenants{% endif %}</span>
        </a>
    </div>
    <nav class="block relative">
        <ul class="navitems flex items-center justify-center h-full">
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'home:home-index' %}">Home</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="{{ request.user.profile.avatar }}" alt="Avatar" />
                    {{ request.user.profile.name }}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/ffffff/expand-arrow.png" alt="Dropdown" />
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100"
                {% if color %}style="background-color: {{ color }}; color: white;"{% endif %}
                >
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="{% url 'users:profile' %}">My Profile</a></li>
                        <li><a href="{% url 'users:profile-edit' %}">Edit Profile</a></li>
                        <li><a href="{% url 'users:profile-settings' %}">Settings</a></li>
                        <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                    </ul>
                </div>
            </li>
            
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}?next={% url 'users:profile-onboarding' %}">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/messages.html
<messages>
    {% if messages %}
    <div x-data="{ showMessage: false }" >
    {% for message in messages %}
    <div class="absolute left-0 right-0 max-w-xl mx-auto mt-3 px-4 z-50 ">
        <div x-cloak class="alert-{{ message.tags }} flex items-center py-3 pl-6 pr-4 bg-blue-500 text-white rounded-lg" role="alert"
        x-show="showMessage" 
        x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
        x-transition:enter="duration-700 ease-out"
        x-transition:enter-start="opacity-0 -translate-y-5"
        x-transition:enter-end="opacity-100 translate-y-0"
        x-transition:leave="duration-200 ease-in"
        x-transition:leave-start="opacity-100 translate-y-0"
        x-transition:leave-end="opacity-0 -translate-y-5">
            <div>
                <div class="text-lg">{{ message }}</div>
            </div>
            <div class="ml-auto cursor-pointer" @click="showMessage = false">
                <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                    <path d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </div>
        </div> 
    </div>
    {% endfor %}
    </div>
    {% endif %}
</messages>