apps/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index_view, name="home-index"),
    path("create_view/", views.create_view, name="create-item"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.profile_view, name="profile"),
    path("edit/", views.profile_edit_view, name="profile-edit"),
    path("onboarding/", views.profile_edit_view, name="profile-onboarding"),
    path("settings/", views.profile_settings_view, name="profile-settings"),
    path(
        "emailchange/", views.profile_emailchange, name="profile-emailchange"
    ),
    path(
        "emailverify/", views.profile_emailverify, name="profile-emailverify"
    ),
    path("delete/", views.profile_delete_view, name="profile-delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.users.views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("apps.home.urls", namespace="home")),
    path("profile/", include("apps.users.urls", namespace="users")),
    path("@<username>/", profile_view, name="profile"),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path("", views.home_view, name="home"),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path("", views.profile_view, name="profile"),
    path("edit/", views.profile_edit_view, name="profile-edit"),
    path("onboarding/", views.profile_edit_view, name="profile-onboarding"),
    path("settings/", views.profile_settings_view, name="profile-settings"),
    path(
        "emailchange/", views.profile_emailchange, name="profile-emailchange"
    ),
    path(
        "emailverify/", views.profile_emailverify, name="profile-emailverify"
    ),
    path("delete/", views.profile_delete_view, name="profile-delete"),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    displayname = models.CharField(max_length=20, null=True, blank=True)
    info = models.TextField(null=True, blank=True) 
    
    def __str__(self):
        return str(self.user)
    
    @property
    def name(self):
        if self.displayname:
            return self.displayname
        return self.user.username 
    
    @property
    def avatar(self):
        if self.image:
            return self.image.url
        return f'{settings.STATIC_URL}images/avatar.svg'

apps/users/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'displayname', 'info' ]
        widgets = {
            'image': forms.FileInput(),
            'displayname' : forms.TextInput(attrs={'placeholder': 'Add display name'}),
            'info' : forms.Textarea(attrs={'rows':3, 'placeholder': 'Add information'})
        }
        
        
class EmailForm(ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['email']

apps/users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.contrib import messages
from django.urls import reverse
from allauth.account.utils import send_email_confirmation

from .forms import ProfileForm
from .forms import EmailForm


def profile_view(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        try:
            profile = request.user.profile
        except Exception:
            return redirect_to_login(request.get_full_path())
    context = {"profile": profile}
    return render(request, "users/profile.html", context=context)


@login_required
def profile_edit_view(request):
    form = ProfileForm(instance=request.user.profile)

    if request.method == "POST":
        form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if form.is_valid():
            form.save()
            return redirect("users:profile")

    onboarding = request.path == reverse("users:profile-onboarding")
    context = {"form": form, "onboarding": onboarding}
    return render(request, "users/profile_edit.html", context=context)


@login_required
def profile_settings_view(request):
    return render(request, "users/profile_settings.html")


@login_required
def profile_emailchange(request):

    if request.htmx:
        form = EmailForm(instance=request.user)
        return render(request, "partials/email_form.html", {"form": form})

    if request.method == "POST":
        form = EmailForm(request.POST, instance=request.user)

        if form.is_valid():

            # Check if the email already exists
            email = form.cleaned_data["email"]
            if (
                User.objects.filter(email=email)
                .exclude(id=request.user.id)
                .exists()
            ):
                messages.warning(request, f"{email} is already in use.")
                return redirect("users:profile-settings")

            form.save()

            # Then Signal updates emailaddress and set verified to False

            # Then send confirmation email
            send_email_confirmation(request, request.user)

        else:
            messages.warning(request, "Form not valid")
        return redirect("users:profile-settings")
    return redirect("home:home-index")


@login_required
def profile_emailverify(request):
    send_email_confirmation(request, request.user)
    return redirect("users:profile-settings")


@login_required
def profile_delete_view(request):
    if request.method == "POST":
        logout(request)
        user = request.user
        user.delete()
        messages.success(request, "Account deleted, what a pity")
        return redirect("home:home-index")

    return render(request, "users/profile_delete.html")

users/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.contrib import messages
from django.urls import reverse
from allauth.account.utils import send_email_confirmation
from .forms import ProfileForm
from .forms import EmailForm


def profile_view(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        try:
            profile = request.user.profile
        except:
            return redirect_to_login(request.get_full_path())
    return render(request, "users/profile.html", {"profile": profile})


@login_required
def profile_edit_view(request):
    form = ProfileForm(instance=request.user.profile)

    if request.method == "POST":
        form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if form.is_valid():
            form.save()
            return redirect("profile")

    if request.path == reverse("profile-onboarding"):
        onboarding = True
    else:
        onboarding = False

    return render(
        request,
        "users/profile_edit.html",
        {"form": form, "onboarding": onboarding},
    )


@login_required
def profile_settings_view(request):
    return render(request, "users/profile_settings.html")


@login_required
def profile_emailchange(request):

    if request.htmx:
        form = EmailForm(instance=request.user)
        return render(request, "partials/email_form.html", {"form": form})

    if request.method == "POST":
        form = EmailForm(request.POST, instance=request.user)

        if form.is_valid():

            # Check if the email already exists
            email = form.cleaned_data["email"]
            if (
                User.objects.filter(email=email)
                .exclude(id=request.user.id)
                .exists()
            ):
                messages.warning(request, f"{email} is already in use.")
                return redirect("profile-settings")

            form.save()

            # Then Signal updates emailaddress and set verified to False

            # Then send confirmation email
            send_email_confirmation(request, request.user)

            return redirect("profile-settings")
        else:
            messages.warning(request, "Form not valid")
            return redirect("profile-settings")

    return redirect("home")


@login_required
def profile_emailverify(request):
    send_email_confirmation(request, request.user)
    return redirect("profile-settings")


@login_required
def profile_delete_view(request):
    user = request.user
    if request.method == "POST":
        logout(request)
        user.delete()
        messages.success(request, "Account deleted, what a pity")
        return redirect("home")

    return render(request, "users/profile_delete.html")

templates/users/profile.html
{% extends 'layouts/blank.html' %}

{% block content %}

<div class="max-w-lg mx-auto flex flex-col items-center pt-20 px-4">
    <img class="w-36 h-36 rounded-full object-cover mb-4" src="{{ profile.avatar }}" />
    <div class="text-center">
        <h1>{{ profile.name }}</h1>
        <div class="text-gray-400 mb-2 -mt-3">@{{ profile.user.username }}</div>
        {% if profile.info %}
        <div class="mt-8 hyphens-auto">{{ profile.info|linebreaksbr }}</div>
        {% endif %}  
    </div>
</div>

{% endblock %}

templates/users/profile_delete.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Delete Account</h1>
<p>Are you sure you want to delete your account?</p>

<form method='POST'>
    {% csrf_token %}
    <button type="submit" class="button-red mt-6">Yes, I want to delete my account</button>
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>

{% endblock %}

templates/users/profile_edit.html
{% extends 'layouts/box.html' %}
{% load static %}

{% block content %}

{% if onboarding %}
<h1 class="mb-4">Complete your Profile</h1>
{% else %}
<h1 class="mb-4">Edit your Profile</h1>
{% endif %}

<div class="text-center flex flex-col items-center">
    <img id="avatar" class="w-36 h-36 rounded-full object-cover my-4" src="{{ user.profile.avatar }}" />
    <div class="text-center max-w-md">
        <h1 id="displayname">{{ user.profile.displayname|default:"" }}</h1>
        <div class="text-gray-400 mb-2 -mt-3">@{{ user.username }}</div>
    </div>
</div>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >Submit</button>
    {% if onboarding %}
    <a class="button button-gray ml-1" href="{% url 'home:home-index' %}">Skip</a>
    {% else %}
    <a class="button button-gray ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    {% endif %}
</form>

<script>
    {% block javascript %}
        {% static 'js/profile_edit.js'%}
    {% endblock javascript %}
</script>

{% endblock %}

templates/users/profile_settings.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1 class="mb-8">Account Settings</h1>

<table class="w-full text-sm text-left text-gray-500">
    <tbody>
        <tr>
            <th scope="row" class="pt-4 pb-1 text-base font-bold text-gray-900">
                Email address
            </th>
            <td id="email-address" class="pt-4 pb-1 pl-4">
                {% if user.email %}{{ user.email }}{% else %}No Email{% endif %}
            </td>
            <td class="pt-4 pb-1 pl-4">
                <a id="email-edit" class="cursor-pointer font-medium text-blue-600 hover:underline"
                    hx-get="{% url 'users:profile-emailchange' %}"
                    hx-target="#email-address"
                    hx-swap="innerHTML" >
                    Edit
                </a>
            </td>
        </tr>
        <tr class="border-b">
            <th scope="row" class="pb-4 font-medium text-gray-900">  
            </th>
            <td class="pb-4 pl-4">
                {% if user.emailaddress_set.first.verified %}
                <span class="text-green-500">Verified</span>{% else %}
                <span class="text-amber-500">Not verified</span>
                {% endif %}
            </td>
            <td class="pb-4 pl-4">
                <a href="{% url 'users:profile-emailverify' %}" class="font-medium text-blue-600 hover:underline">
                    {% if not user.emailaddress_set.first.verified %}Verify{% endif %}
                </a>
            </td>
        </tr>

        <tr class="border-b">
            <th scope="row" class="py-4 text-base font-bold text-gray-900">
                Delete Account
            </th>
            <td class="py-4 pl-4">
                Once deleted, account is gone. Forever.
            </td>
            <td class="py-4 pl-4">
                <a href="{% url 'users:profile-delete' %}" class="font-medium text-red-600 hover:underline">
                    Delete
                </a>
            </td>
        </tr>
    </tbody>
</table>


{% endblock %}